-- ============================================================
--  UniTask — Script de Criação do Banco de Dados (PostgreSQL)
--  Versão: 2.0  |  Maio de 2026
--  Migrado de MySQL para PostgreSQL
-- ============================================================

-- Criação do banco (executar conectado ao banco "postgres")
-- CREATE DATABASE unitask ENCODING 'UTF8';
-- \c unitask

-- ============================================================
--  TABELA: usuario
-- ============================================================
CREATE TABLE usuario (
    id_usuario  INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    nome        VARCHAR(100)    NOT NULL,
    email       VARCHAR(150)    NOT NULL,
    senha_hash  VARCHAR(255)    NOT NULL,
    foto_perfil TEXT,
    criado_em   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_usuario PRIMARY KEY (id_usuario),
    CONSTRAINT uk_usuario_email UNIQUE (email)
);

-- ============================================================
--  TABELA: grupo
-- ============================================================
CREATE TABLE grupo (
    id_grupo        INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_admin        INTEGER         NOT NULL,
    nome            VARCHAR(100)    NOT NULL,
    descricao       TEXT,
    codigo_convite  VARCHAR(20)     NOT NULL,
    criado_em       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_grupo PRIMARY KEY (id_grupo),
    CONSTRAINT uk_grupo_codigo UNIQUE (codigo_convite),
    CONSTRAINT fk_grupo_admin FOREIGN KEY (id_admin)
        REFERENCES usuario (id_usuario)
        ON DELETE RESTRICT
        ON UPDATE CASCADE
);

-- ============================================================
--  TABELA: tarefa
-- ============================================================
CREATE TABLE tarefa (
    id_tarefa       INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_usuario      INTEGER         NOT NULL,
    titulo          VARCHAR(100)    NOT NULL,
    descricao       TEXT,
    prioridade      VARCHAR(10)     NOT NULL DEFAULT 'media',
    status          VARCHAR(15)     NOT NULL DEFAULT 'pendente',
    prazo           TIMESTAMP,
    concluido_em    TIMESTAMP,
    criado_em       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tarefa PRIMARY KEY (id_tarefa),
    CONSTRAINT chk_tarefa_prioridade CHECK (prioridade IN ('baixa','media','alta')),
    CONSTRAINT chk_tarefa_status CHECK (status IN ('pendente','concluida')),
    CONSTRAINT fk_tarefa_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
--  TABELA: grupo_membro  (N:M — usuario × grupo)
-- ============================================================
CREATE TABLE grupo_membro (
    id_usuario  INTEGER         NOT NULL,
    id_grupo    INTEGER         NOT NULL,
    papel       VARCHAR(10)     NOT NULL DEFAULT 'membro',
    entrou_em   TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_grupo_membro PRIMARY KEY (id_usuario, id_grupo),
    CONSTRAINT chk_gm_papel CHECK (papel IN ('admin','membro')),
    CONSTRAINT fk_gm_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_gm_grupo FOREIGN KEY (id_grupo)
        REFERENCES grupo (id_grupo)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
--  TABELA: tarefa_grupo  (N:M — tarefa × grupo)
-- ============================================================
CREATE TABLE tarefa_grupo (
    id_tarefa           INTEGER     NOT NULL,
    id_grupo            INTEGER     NOT NULL,
    compartilhado_em    TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_tarefa_grupo PRIMARY KEY (id_tarefa, id_grupo),
    CONSTRAINT fk_tg_tarefa FOREIGN KEY (id_tarefa)
        REFERENCES tarefa (id_tarefa)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_tg_grupo FOREIGN KEY (id_grupo)
        REFERENCES grupo (id_grupo)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
--  TABELA: notificacao
-- ============================================================
CREATE TABLE notificacao (
    id_notificacao  INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    id_tarefa       INTEGER     NOT NULL,
    id_usuario      INTEGER     NOT NULL,
    tipo            VARCHAR(10) NOT NULL,
    mensagem        TEXT        NOT NULL,
    enviado_em      TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,
    lido            BOOLEAN     NOT NULL DEFAULT FALSE,

    CONSTRAINT pk_notificacao PRIMARY KEY (id_notificacao),
    CONSTRAINT chk_notif_tipo CHECK (tipo IN ('24h','1h','vencida')),
    CONSTRAINT fk_notif_tarefa FOREIGN KEY (id_tarefa)
        REFERENCES tarefa (id_tarefa)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_notif_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
--  TABELA: comentario
-- ============================================================
CREATE TABLE comentario (
    id_comentario   INTEGER     GENERATED BY DEFAULT AS IDENTITY,
    id_tarefa       INTEGER     NOT NULL,
    id_usuario      INTEGER     NOT NULL,
    conteudo        TEXT        NOT NULL,
    criado_em       TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_comentario PRIMARY KEY (id_comentario),
    CONSTRAINT fk_com_tarefa FOREIGN KEY (id_tarefa)
        REFERENCES tarefa (id_tarefa)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_com_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
--  TABELA: anexo
-- ============================================================
CREATE TABLE anexo (
    id_anexo        INTEGER         GENERATED BY DEFAULT AS IDENTITY,
    id_tarefa       INTEGER         NOT NULL,
    id_usuario      INTEGER         NOT NULL,
    nome_arquivo    VARCHAR(255)    NOT NULL,
    url             VARCHAR(500)    NOT NULL,
    criado_em       TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_anexo PRIMARY KEY (id_anexo),
    CONSTRAINT fk_anx_tarefa FOREIGN KEY (id_tarefa)
        REFERENCES tarefa (id_tarefa)
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_anx_usuario FOREIGN KEY (id_usuario)
        REFERENCES usuario (id_usuario)
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- ============================================================
--  ÍNDICES adicionais para performance
-- ============================================================
CREATE INDEX idx_tarefa_usuario    ON tarefa       (id_usuario);
CREATE INDEX idx_tarefa_status     ON tarefa       (status);
CREATE INDEX idx_tarefa_prazo      ON tarefa       (prazo);
CREATE INDEX idx_notif_usuario     ON notificacao  (id_usuario);
CREATE INDEX idx_notif_lido        ON notificacao  (lido);
CREATE INDEX idx_grupo_admin       ON grupo        (id_admin);
CREATE INDEX idx_comentario_tarefa ON comentario   (id_tarefa);
CREATE INDEX idx_anexo_tarefa      ON anexo        (id_tarefa);

-- ============================================================
--  FIM DO SCRIPT
-- ============================================================
